### ISSUE TITLE
Bug: iPad support?

### ISSUE THREAD

**Issue by taoeffect** [ReticentJohn/Amaroq#18]
On my iPad Pro (the smaller one) Amaroq is *tiny*, leaving most of the screen real estate black and unused, and the app itself difficult to use and read.

**Comment by jelle619** [comment]
Amaroq is iPhone (and iPod Touch, I guess?) only. Your iPad is trying to run the app as if it were an iPhone, and that’s why you see those black borders. Since it’s a blown up iPhone app, the app will indeed be a little more difficult to use than on an actual iPhone.

I’ve heard iPad support is eventually coming, so stay tuned!

**Comment by rightmeow666** [comment]
Adds support for iPad, see #119

**Comment by theoden8** [comment]
Any update on this?

**Comment by ruta0** [comment]
My PR #119 is still up there since 2019. I don't think the iPad support is going to move forward. So closing PR for now.
