### ISSUE TITLE
Push notifications are unreliable

### ISSUE THREAD

**Issue by wolfteeth** [ReticentJohn/Amaroq#36]
I have never reliably gotten push notifications even though they are enabled both in the app and at the iOS settings level for Amaroq.

I've successfully gotten push notifications 2-3 times but usually I just have to check the app manually to see if I have notifications. I'm not sure what was different about the times they worked vs. times they didn't. I use a VPN much of the time but using my home wifi without it didn't make a difference. I typically force close Amaroq when I'm not actively using it.

I reliably get push notifications from other apps that I treat in a similar way.

Could this be something wrong with the notification server? Tusky for Android has a similar-sounding issue: https://github.com/Vavassor/Tusky/issues/84

**Comment by ReticentJohn** [comment]
Amaroq's push notifications are silent - they only trigger a background refresh which creates the actual notification you see locally. If you force-quit the app it will have no way to perform a background refresh, so you see no notification.

It's designed this way so that Amaroq's push server, Firebase, and APNS never see the contents of a notification.

**Comment by wolfteeth** [comment]
Tried leaving the app open in the background today and got no push notifications that way either. App didn't refresh until I brought it to the foreground again.
