### ISSUE TITLE
notifications arrive even when disabled

### ISSUE THREAD

**Issue by nightpool** [ReticentJohn/Amaroq#48]
hey, I know this is probably a known problem, but I just wanted to leave a tracking issue for this because i've heard a lot of pain from users who suddenly had notifications turned on last night even though they have them disabled in the app settings

To summarize, after the move away from silent notifications, users aren't able to customize their notification preferences from the amaroq settings anymore. these settings need to be propagated to the server so it can respect these users preferences. 

this is a pretty big issue for people with active accounts

**Comment by ReticentJohn** [comment]
Will be fast-tracking this fix to the App Store. Thanks for bringing it to my attention, and I am terribly sorry for any annoying notification spam this had created.

For those who have not seen my explanation earlier on mastodon.social, this was caused by changing from silent notifications to standard notifications, due to iOS11 changing the behavior of how background refreshing and silent notifications work. As a result notifications have stopped behaving as expected, because previously notifications were filtered locally instead of at the server level. This was a huge oversight on my part.
