### ISSUE TITLE
Answering toot break privacy settings

### ISSUE THREAD

**Issue by mathias-b** [ReticentJohn/Amaroq#50]
Hello,

Since I have protected my account and post as "Followers only" Amaroq break my privacy settings. When I answer some toot which is not posted as "Followers only" Amaroq use the same settings and what I post goes public.

Thanks in advance,

🙇

**Comment by ReticentJohn** [comment]
This is by design. Having your privacy settings set to "Followers only" will ensure that your posts will always be set to "Followers only", except when replying. A reply will always follow the privacy level that the original toot was set at by default - this is mostly to ensure that those who set their privacy settings to "Public" don't default to reply publicly to "Unlisted", "Followers only", or "Direct" toots. When you're replying to a toot, the privacy will always show clearly in the compose view, and you can manually set it to any desired privacy level from there.
![img_9467](https://user-images.githubusercontent.com/573400/30483621-8606df7a-99f5-11e7-8845-7df0c9a13eb4.jpg)

**Comment by mathias-b** [comment]
Okay, thanks for explaining this. 👍 

But:
- It doesn't work this way on the standard website
- I missed it a lot fo times, when you need to reply quickly to someone it can be complicated

Have a great day
