### ISSUE TITLE
Feature request: WebM playback

### ISSUE THREAD

**Issue by daprice** [ReticentJohn/Amaroq#6]
Since WebM files are commonly posted on Mastodon, it would be nice to have a way to view them. VLC provides a [library](https://wiki.videolan.org/VLCKit/) that I believe supports WebM playback.

Since there wouldn't be native hardware acceleration, I wouldn't expect them to play inline (to conserve battery life), just have a working thumbnail and play when opened.

**Comment by ReticentJohn** [comment]
Not a fan of dropping any GPL licensed code in the app (it's just toxic for the App Store), but I have had [OGVKit](https://github.com/brion/OGVKit) in my crosshairs as a potential way of bringing support. I'd really much rather webm just be dropped entirely until its more widely adopted, because it already can't be played in any safari browser, but I suppose we're at the mercy of what the API hands us.
